/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-02-28 20:19:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import techConnect.ProjectDummy;

public final class projects_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("techConnect.ProjectDummy");
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<!-- https://bootsnipp.com/snippets/mMBqZ -->\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Register</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\" >\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" ></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js\" ></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js\" ></script>\r\n");
      out.write("    <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("    <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.2.0/css/all.css\" integrity=\"sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ\" crossorigin=\"anonymous\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .social-card-header i {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            color:#FFF;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!----nav bar---->\r\n");
      out.write("<section id=\"nav-bar\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"assets/icon.png\"></a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"index.jsp\">Home <span class=\"sr-only\"></span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"projects.jsp\">Projects</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"login.jsp\">Sign In</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link \" href=\"about.jsp\">About</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class = \"nav-item\">\r\n");
      out.write("                    <a class = \"nav-link\" href=\"managementPage.jsp\">Help</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h3 class=\"pb-3 mb-4 font-italic border-bottom\">\r\n");
      out.write("        Card Styles\r\n");
      out.write("    </h3>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"card flex-md-row mb-4 shadow-sm h-md-250\">\r\n");
      out.write("                <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                    ");
ProjectDummy projectDummy = new ProjectDummy();
      out.write("\r\n");
      out.write("                    <strong class=\"d-inline-block mb-2 text-primary\">");
      out.print( projectDummy.setProjectTitle().get(0));
      out.write("</strong>\r\n");
      out.write("                    <h6 class=\"mb-0\">\r\n");
      out.write("                        <a class=\"text-dark\" href=\"#\">");
      out.print( projectDummy.setNeed().get(0));
      out.write("</a>\r\n");
      out.write("                    </h6>\r\n");
      out.write("                    <div class=\"mb-1 text-muted small\">");
      out.print(projectDummy.setProjectDate().get(0));
      out.write("</div>\r\n");
      out.write("                    <p class=\"card-text mb-auto\">");
      out.print(projectDummy.setContact().get(0));
      out.write("</p>\r\n");
      out.write("                    <a class=\"btn btn-outline-primary btn-sm\" role=\"button\" href=\"http://www.jquery2dotnet.com/\">Continue reading</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img class=\"card-img-right flex-auto d-none d-lg-block\" alt=\"Thumbnail [200x250]\" src=\"//placeimg.com/250/250/arch\" style=\"width: 200px; height: 250px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"card flex-md-row mb-4 shadow-sm h-md-250\">\r\n");
      out.write("                <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                    <strong class=\"d-inline-block mb-2 text-success\">");
      out.print( projectDummy.setProjectTitle().get(1));
      out.write("</strong>\r\n");
      out.write("                    <h6 class=\"mb-0\">\r\n");
      out.write("                        <a class=\"text-dark\" href=\"#\">");
      out.print( projectDummy.setNeed().get(1));
      out.write("</a>\r\n");
      out.write("                    </h6>\r\n");
      out.write("                    <div class=\"mb-1 text-muted small\">");
      out.print(projectDummy.setProjectDate().get(1));
      out.write("</div>\r\n");
      out.write("                    <p class=\"card-text mb-auto\">");
      out.print(projectDummy.setContact().get(1));
      out.write("</p>\r\n");
      out.write("                    <a class=\"btn btn-outline-success btn-sm\" href=\"http://www.jquery2dotnet.com/\">Continue reading</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img class=\"card-img-right flex-auto d-none d-lg-block\" alt=\"Thumbnail [200x250]\" src=\"//placeimg.com/250/250/nature\" style=\"width: 200px; height: 250px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"card border-primary flex-md-row mb-4 shadow-sm h-md-250\">\r\n");
      out.write("                <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                    <strong class=\"d-inline-block mb-2 text-primary\">");
      out.print( projectDummy.setProjectTitle().get(2));
      out.write("</strong>\r\n");
      out.write("                    <h6 class=\"mb-0\">\r\n");
      out.write("                        <a class=\"text-dark\" href=\"#\">");
      out.print( projectDummy.setNeed().get(2));
      out.write("</a>\r\n");
      out.write("                    </h6>\r\n");
      out.write("                    <div class=\"mb-1 text-muted small\">");
      out.print(projectDummy.setProjectDate().get(2));
      out.write("</div>\r\n");
      out.write("                    <p class=\"card-text mb-auto\">");
      out.print(projectDummy.setContact().get(2));
      out.write("</p>\r\n");
      out.write("                    <a class=\"btn btn-outline-primary btn-sm\" role=\"button\" href=\"http://www.jquery2dotnet.com/\">Continue reading</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img class=\"card-img-right flex-auto d-none d-lg-block\" alt=\"Thumbnail [200x250]\" src=\"//placeimg.com/250/250/arch\" style=\"width: 200px; height: 250px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"card border-success flex-md-row mb-4 shadow-sm h-md-250\">\r\n");
      out.write("                <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                    <strong class=\"d-inline-block mb-2 text-success\">");
      out.print( projectDummy.setProjectTitle().get(3));
      out.write("</strong>\r\n");
      out.write("                    <h6 class=\"mb-0\">\r\n");
      out.write("                        <a class=\"text-dark\" href=\"#\">");
      out.print( projectDummy.setNeed().get(3));
      out.write("</a>\r\n");
      out.write("                    </h6>\r\n");
      out.write("                    <div class=\"mb-1 text-muted small\">");
      out.print(projectDummy.setProjectDate().get(3));
      out.write("</div>\r\n");
      out.write("                    <p class=\"card-text mb-auto\">");
      out.print(projectDummy.setContact().get(3));
      out.write("</p>\r\n");
      out.write("                    <a class=\"btn btn-outline-success btn-sm\" href=\"http://www.jquery2dotnet.com/\">Continue reading</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img class=\"card-img-right flex-auto d-none d-lg-block\" alt=\"Thumbnail [200x250]\" src=\"//placeimg.com/250/250/nature\" style=\"width: 200px; height: 250px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"card text-white bg-primary flex-md-row mb-4 shadow-sm h-md-250\">\r\n");
      out.write("                <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                    <strong class=\"d-inline-block mb-2 text-white\">");
      out.print( projectDummy.setProjectTitle().get(4));
      out.write("</strong>\r\n");
      out.write("                    <h6 class=\"mb-0\">\r\n");
      out.write("                        <a class=\"text-white\" href=\"#\">");
      out.print( projectDummy.setNeed().get(4));
      out.write("</a>\r\n");
      out.write("                    </h6>\r\n");
      out.write("                    <div class=\"mb-1 text-white-50 small\">");
      out.print(projectDummy.setProjectDate().get(4));
      out.write("</div>\r\n");
      out.write("                    <p class=\"card-text mb-auto\">");
      out.print(projectDummy.setContact().get(4));
      out.write("</p>\r\n");
      out.write("                    <a class=\"btn btn-outline-light btn-sm\" role=\"button\" href=\"http://www.jquery2dotnet.com/\">Continue reading</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img class=\"card-img-right flex-auto d-none d-lg-block\" alt=\"Thumbnail [200x250]\" src=\"//placeimg.com/250/250/arch\" style=\"width: 200px; height: 250px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"card text-white bg-success flex-md-row mb-4 shadow-sm h-md-250\">\r\n");
      out.write("                <div class=\"card-body d-flex flex-column align-items-start\">\r\n");
      out.write("                    <strong class=\"d-inline-block mb-2 text-white\">");
      out.print( projectDummy.setProjectTitle().get(5));
      out.write("</strong>\r\n");
      out.write("                    <h6 class=\"mb-0\">\r\n");
      out.write("                        <a class=\"text-white\" href=\"#\">");
      out.print( projectDummy.setNeed().get(5));
      out.write("</a>\r\n");
      out.write("                    </h6>\r\n");
      out.write("                    <div class=\"mb-1 text-white-50 small\">");
      out.print(projectDummy.setProjectDate().get(5));
      out.write("</div>\r\n");
      out.write("                    <p class=\"card-text mb-auto\">");
      out.print(projectDummy.setContact().get(5));
      out.write("</p>\r\n");
      out.write("                    <a class=\"btn btn-outline-light btn-sm\" href=\"http://www.jquery2dotnet.com/\">Continue reading</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img class=\"card-img-right flex-auto d-none d-lg-block\" alt=\"Thumbnail [200x250]\" src=\"//placeimg.com/250/250/nature\" style=\"width: 200px; height: 250px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card mb-4\">\r\n");
      out.write("                <img class=\"card-img-top\" src=\"//placeimg.com/290/180/any\" alt=\"Card image cap\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">");
      out.print( projectDummy.setProjectTitle().get(6));
      out.write("</h5>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setProjectDate().get(6) + "\n" +  projectDummy.setNeed().get(6));
      out.write("</p>\r\n");
      out.write("                    <a href=\"http://www.jquery2dotnet.com/\" class=\"btn btn-outline-dark btn-sm\">Go somewhere</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card mb-4 border-dark\">\r\n");
      out.write("                <img class=\"card-img-top\" src=\"//placeimg.com/290/180/any\" alt=\"Card image cap\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">");
      out.print( projectDummy.setProjectTitle().get(0));
      out.write("</h5>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setProjectDate().get(0) +"\n" +  projectDummy.setNeed().get(0));
      out.write("</p>\r\n");
      out.write("                    <a href=\"http://www.jquery2dotnet.com/\" class=\"btn btn-dark btn-sm\">Go somewhere</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card mb-4 text-white bg-dark\">\r\n");
      out.write("                <img class=\"card-img-top\" src=\"//placeimg.com/290/180/any\" alt=\"Card image cap\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">");
      out.print( projectDummy.setProjectTitle().get(1));
      out.write("</h5>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setProjectDate().get(1) +"\n" +  projectDummy.setNeed().get(1));
      out.write("</p>\r\n");
      out.write("                    <a href=\"http://www.jquery2dotnet.com/\" class=\"btn btn-outline-light btn-sm\">Go somewhere</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <h3 class=\"mt-3 pb-3 mb-4 font-italic border-bottom\">\r\n");
      out.write("        Image overlays\r\n");
      out.write("    </h3>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-8\">\r\n");
      out.write("            <div class=\"card mb-4 bg-dark text-white\">\r\n");
      out.write("                <img class=\"card-img\" src=\"//placeimg.com/780/270/any\" alt=\"Card image\">\r\n");
      out.write("                <div class=\"card-img-overlay\">\r\n");
      out.write("                    <h5 class=\"card-title\">");
      out.print( projectDummy.setProjectTitle().get(2));
      out.write("</h5>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setNeed().get(2));
      out.write("</p>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setProjectDate().get(2));
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card mb-4 bg-dark text-white\">\r\n");
      out.write("                <img class=\"card-img\" src=\"//placeimg.com/250/180/any\" alt=\"Card image\">\r\n");
      out.write("                <div class=\"card-img-overlay\">\r\n");
      out.write("                    <h5 class=\"card-title\">");
      out.print( projectDummy.setProjectTitle().get(3));
      out.write("</h5>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print( projectDummy.setNeed().get(6));
      out.write("</p>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setProjectDate().get(2));
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <h3 class=\"mt-3 pb-3 mb-4 font-italic border-bottom\">\r\n");
      out.write("        More Cards\r\n");
      out.write("    </h3>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img class=\"card-img-top\" src=\"//placeimg.com/280/180/tech\" alt=\"Card image cap\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title border-bottom pb-3\">");
      out.print( projectDummy.setProjectTitle().get(4));
      out.write("</h5>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setNeed().get(4));
      out.write("</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-info float-right\">Read more <i class=\"fas fa-angle-double-right\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <img class=\"card-img-top\" src=\"//placeimg.com/280/180/tech\" alt=\"Card image cap\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title border-bottom pb-3\">");
      out.print( projectDummy.setProjectTitle().get(5));
      out.write("</h5>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setNeed().get(5));
      out.write("</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-info float-right\">Read more <i class=\"fas fa-angle-double-right\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card bg-light\">\r\n");
      out.write("                <img class=\"card-img-top\" src=\"//placeimg.com/280/180/tech\" alt=\"Card image cap\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title border-bottom pb-3\">");
      out.print( projectDummy.setProjectTitle().get(6));
      out.write("</h5>\r\n");
      out.write("                    <p class=\"card-text\">");
      out.print(projectDummy.setNeed().get(6));
      out.write(".</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm btn-info float-right\">Read more <i class=\"fas fa-angle-double-right\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav aria-label=\"Page navigation example\">\r\n");
      out.write("        <ul class=\"pagination\">\r\n");
      out.write("            <li class=\"page-item\">\r\n");
      out.write("                <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("                    <span class=\"sr-only\">Previous</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("            <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("            <li class=\"page-item\">\r\n");
      out.write("                <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("                    <span class=\"sr-only\">Next</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
